---
  ###########################################################
  #           Playbook to query dCloud switches             #
  ###########################################################
  - name: Retrieve facts from dCloud switches
    hosts: nx-os
    connection: local

    tasks:
      - name: "Retrieving NXOS facts."
        nxos_facts:
          host: "{{inventory_hostname}}"
          transport: nxapi
        register: nxos_info

      - name: "Hi! Here are my facts."
        debug: msg="{{nxos_info}}"
